-- 브랜드 셋팅
insert into brand(id, name, is_deleted, created_at, updated_at) values (1, 'A',false,37700, now(), now()); -- 1
insert into brand(id, name, is_deleted, created_at, updated_at) values (2, 'B',false,37600, now(), now());
insert into brand(id, name, is_deleted, created_at, updated_at) values (3, 'C',false,37100, now(), now());
insert into brand(id, name, is_deleted, created_at, updated_at) values (4, 'D',false,36100, now(), now());
insert into brand(id, name, is_deleted, created_at, updated_at) values (5, 'E',false,37700, now(), now());
insert into brand(id, name, is_deleted, created_at, updated_at) values (6, 'F',false,39600, now(), now());
insert into brand(id, name, is_deleted, created_at, updated_at) values (7, 'G',false,37200, now(), now());
insert into brand(id, name, is_deleted, created_at, updated_at) values (8, 'H',false,37600, now(), now());
insert into brand(id, name, is_deleted, created_at, updated_at) values (9, 'I',false,39000, now(), now());


-- product 셋팅
insert into product(id, created_at, updated_at, category, price, brand_id) values (1, now(), now(), 1, 11200, 1, 1);
insert into product(id, created_at, updated_at, category, price, brand_id) values (2, now(), now(), 1, 5500, 2, 1);
insert into product(id, created_at, updated_at, category, price, brand_id) values (3, now(), now(), 1, 4200, 3, 1);
insert into product(id, created_at, updated_at, category, price, brand_id) values (4, now(), now(), 1, 9000, 4, 1);
insert into product(id, created_at, updated_at, category, price, brand_id) values (5, now(), now(), 1, 2000, 5, 1);
insert into product(id, created_at, updated_at, category, price, brand_id) values (6, now(), now(), 1, 1700, 6, 1);
insert into product(id, created_at, updated_at, category, price, brand_id) values (7, now(), now(), 1, 1800, 7, 1);
insert into product(id, created_at, updated_at, category, price, brand_id) values (8, now(), now(), 1, 2300, 8, 1);
insert into product(id, created_at, updated_at, category, price, brand_id) values (9, now(), now(), 2, 10500, 1, 2);
insert into product(id, created_at, updated_at, category, price, brand_id) values (10, now(), now(), 2, 5900, 2, 2);
insert into product(id, created_at, updated_at, category, price, brand_id) values (11, now(), now(), 2, 3800, 3, 2);
insert into product(id, created_at, updated_at, category, price, brand_id) values (12, now(), now(), 2, 9100, 4, 2);
insert into product(id, created_at, updated_at, category, price, brand_id) values (13, now(), now(), 2, 2100, 5, 2);
insert into product(id, created_at, updated_at, category, price, brand_id) values (14, now(), now(), 2, 2000, 6, 2);
insert into product(id, created_at, updated_at, category, price, brand_id) values (15, now(), now(), 2, 2000, 7, 2);
insert into product(id, created_at, updated_at, category, price, brand_id) values (16, now(), now(), 2, 2200, 8, 2);
insert into product(id, created_at, updated_at, category, price, brand_id) values (17, now(), now(), 3, 10000, 1, 3);
insert into product(id, created_at, updated_at, category, price, brand_id) values (18, now(), now(), 3, 6200, 2, 3);
insert into product(id, created_at, updated_at, category, price, brand_id) values (19, now(), now(), 3, 3300, 3, 3);
insert into product(id, created_at, updated_at, category, price, brand_id) values (20, now(), now(), 3, 9200, 4, 3);
insert into product(id, created_at, updated_at, category, price, brand_id) values (21, now(), now(), 3, 2200, 5, 3);
insert into product(id, created_at, updated_at, category, price, brand_id) values (22, now(), now(), 3, 1900, 6, 3);
insert into product(id, created_at, updated_at, category, price, brand_id) values (23, now(), now(), 3, 2200, 7, 3);
insert into product(id, created_at, updated_at, category, price, brand_id) values (24, now(), now(), 3, 2100, 8, 3);
insert into product(id, created_at, updated_at, category, price, brand_id) values (25, now(), now(), 4, 10100, 1, 4);
insert into product(id, created_at, updated_at, category, price, brand_id) values (26, now(), now(), 4, 5100, 2, 4);
insert into product(id, created_at, updated_at, category, price, brand_id) values (27, now(), now(), 4, 3000, 3, 4);
insert into product(id, created_at, updated_at, category, price, brand_id) values (28, now(), now(), 4, 9500, 4, 4);
insert into product(id, created_at, updated_at, category, price, brand_id) values (29, now(), now(), 4, 2500, 5, 4);
insert into product(id, created_at, updated_at, category, price, brand_id) values (30, now(), now(), 4, 1500, 6, 4);
insert into product(id, created_at, updated_at, category, price, brand_id) values (31, now(), now(), 4, 2400, 7, 4);
insert into product(id, created_at, updated_at, category, price, brand_id) values (32, now(), now(), 4, 2000, 8, 4);
insert into product(id, created_at, updated_at, category, price, brand_id) values (33, now(), now(), 5, 10700, 1, 5);
insert into product(id, created_at, updated_at, category, price, brand_id) values (34, now(), now(), 5, 5000, 2, 5);
insert into product(id, created_at, updated_at, category, price, brand_id) values (35, now(), now(), 5, 3800, 3, 5);
insert into product(id, created_at, updated_at, category, price, brand_id) values (36, now(), now(), 5, 9900, 4, 5);
insert into product(id, created_at, updated_at, category, price, brand_id) values (37, now(), now(), 5, 2300, 5, 5);
insert into product(id, created_at, updated_at, category, price, brand_id) values (38, now(), now(), 5, 1800, 6, 5);
insert into product(id, created_at, updated_at, category, price, brand_id) values (39, now(), now(), 5, 2100, 7, 5);
insert into product(id, created_at, updated_at, category, price, brand_id) values (40, now(), now(), 5, 2100, 8, 5);
insert into product(id, created_at, updated_at, category, price, brand_id) values (41, now(), now(), 6, 11200, 1, 6);
insert into product(id, created_at, updated_at, category, price, brand_id) values (42, now(), now(), 6, 7200, 2, 6);
insert into product(id, created_at, updated_at, category, price, brand_id) values (43, now(), now(), 6, 4000, 3, 6);
insert into product(id, created_at, updated_at, category, price, brand_id) values (44, now(), now(), 6, 9300, 4, 6);
insert into product(id, created_at, updated_at, category, price, brand_id) values (45, now(), now(), 6, 2100, 5, 6);
insert into product(id, created_at, updated_at, category, price, brand_id) values (46, now(), now(), 6, 1600, 6, 6);
insert into product(id, created_at, updated_at, category, price, brand_id) values (47, now(), now(), 6, 2300, 7, 6);
insert into product(id, created_at, updated_at, category, price, brand_id) values (48, now(), now(), 6, 1900, 8, 6);
insert into product(id, created_at, updated_at, category, price, brand_id) values (49, now(), now(), 7, 10500, 1, 7);
insert into product(id, created_at, updated_at, category, price, brand_id) values (50, now(), now(), 7, 5800, 2, 7);
insert into product(id, created_at, updated_at, category, price, brand_id) values (51, now(), now(), 7, 3900, 3, 7);
insert into product(id, created_at, updated_at, category, price, brand_id) values (52, now(), now(), 7, 9000, 4, 7);
insert into product(id, created_at, updated_at, category, price, brand_id) values (53, now(), now(), 7, 2200, 5, 7);
insert into product(id, created_at, updated_at, category, price, brand_id) values (54, now(), now(), 7, 1700, 6, 7);
insert into product(id, created_at, updated_at, category, price, brand_id) values (55, now(), now(), 7, 2100, 7, 7);
insert into product(id, created_at, updated_at, category, price, brand_id) values (56, now(), now(), 7, 2000, 8, 7);
insert into product(id, created_at, updated_at, category, price, brand_id) values (57, now(), now(), 8, 10800, 1, 8);
insert into product(id, created_at, updated_at, category, price, brand_id) values (58, now(), now(), 8, 6300, 2, 8);
insert into product(id, created_at, updated_at, category, price, brand_id) values (59, now(), now(), 8, 3100, 3, 8);
insert into product(id, created_at, updated_at, category, price, brand_id) values (60, now(), now(), 8, 9700, 4, 8);
insert into product(id, created_at, updated_at, category, price, brand_id) values (61, now(), now(), 8, 2100, 5, 8);
insert into product(id, created_at, updated_at, category, price, brand_id) values (62, now(), now(), 8, 1600, 6, 8);
insert into product(id, created_at, updated_at, category, price, brand_id) values (63, now(), now(), 8, 2000, 7, 8);
insert into product(id, created_at, updated_at, category, price, brand_id) values (64, now(), now(), 8, 2000, 8, 8);
insert into product(id, created_at, updated_at, category, price, brand_id) values (65, now(), now(), 9, 11400, 1, 9);
insert into product(id, created_at, updated_at, category, price, brand_id) values (66, now(), now(), 9, 6700, 2, 9);
insert into product(id, created_at, updated_at, category, price, brand_id) values (67, now(), now(), 9, 3200, 3, 9);
insert into product(id, created_at, updated_at, category, price, brand_id) values (68, now(), now(), 9, 9500, 4, 9);
insert into product(id, created_at, updated_at, category, price, brand_id) values (69, now(), now(), 9, 2400, 5, 9);
insert into product(id, created_at, updated_at, category, price, brand_id) values (70, now(), now(), 9, 1700, 6, 9);
insert into product(id, created_at, updated_at, category, price, brand_id) values (71, now(), now(), 9, 1700, 7, 9);
insert into product(id, created_at, updated_at, category, price, brand_id) values (72, now(), now(), 9, 2400, 8, 9);